[build]
  command = "npm run build"
  publish = "build"
  base = "/"
  environment = { NODE_VERSION = "18.19.1" }

[context.production]
  command = "bash scripts/sync-changelog.sh && bash scripts/generate-table-json.sh && bash scripts/sync-data.sh && npm ci && npm run build"

[context.deploy-preview]
  command = "bash scripts/sync-changelog.sh && bash scripts/generate-table-json.sh && bash scripts/sync-data.sh && npm ci && npm run build"

